=== dd-harp/MicroMoB-connector/schema/adult_par.json
{
  "$ref": "#/definitions/AdultPar",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AdultPar": {
      "additionalProperties": false,
      "description": "Parameters for the Ross-Macdonal adult mosquito model.",
      "properties": {
        "stochastic": {
         "items": {
            "type": "boolean"
          },
          "type": "array"
        },
        "f": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "q": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "eip": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "p": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "psi" : {
          "items" : {
            "type": "array"
          },
          "type": "array"
        },
        "nu" : {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "M": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "Y": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "Z": {
          "items": {
            "type": "number"
          },
          "type": "array"
        }
      },
      "required": [
        "stochastic",
        "f",
        "q",
        "eip",
        "p",
        "psi",
        "nu",
        "M",
        "Y",
        "Z"
      ],
      "type": "object"
    }
  }
}

=== dd-harp/MicroMoB-connector/test/adult_par.json
{
  "stochastic": [true],
  "f": [0.3],
  "q": [0.9],
  "eip": [10],
    "p": [0.46224601027, 0.46998972523, 0.47772885025, 0.48546109206, 0.49318415943, 0.50089576385, 0.5085936202, 0.51627544745, 0.5239389693, 0.53158191488, 0.53920201943, 0.54679702494, 0.55436468085, 0.5619027447, 0.5694089828, 0.57688117089, 0.5843170948, 0.5917145511, 0.59907134776, 0.60638530482, 0.61365425498, 0.6208760443, 0.62804853281, 0.63516959514, 0.64223712118, 0.64924901665, 0.65620320378, 0.66309762191, 0.66993022805, 0.67669899757, 0.68340192473, 0.69003702331, 0.69660232719, 0.70309589093, 0.70951579033, 0.71586012305, 0.72212700913, 0.72831459155, 0.7344210368, 0.7404445354, 0.74638330247, 0.75223557821, 0.75799962847, 0.76367374525, 0.76925624717, 0.77474548003, 0.78013981723, 0.78543766033, 0.79063743946, 0.79573761382, 0.8007366721, 0.80563313298, 0.81042554554, 0.81511248968, 0.81969257655, 0.82416444899, 0.82852678186, 0.83277828254, 0.83691769119, 0.84094378122, 0.84485535963, 0.84865126731, 0.85233037947, 0.85589160591, 0.85933389134, 0.86265621576, 0.86585759468, 0.86893707947, 0.87189375761, 0.87472675297, 0.87743522607, 0.88001837434, 0.88247543233, 0.88480567197, 0.88700840274, 0.88908297194, 0.89102876483, 0.89284520483, 0.89453175368, 0.89608791162, 0.89751321754, 0.89880724908, 0.89996962279, 0.90099999424, 0.9018980581, 0.90266354827, 0.9032962379, 0.90379593952, 0.90416250506, 0.90439582589, 0.90449583288, 0.90446249639, 0.90429582631, 0.90399587201, 0.90356272239, 0.90299650579, 0.90229739, 0.90146558217, 0.9005013288, 0.8994049156, 0.89817666748, 0.89681694839, 0.89532616124, 0.89370474778, 0.89195318848, 0.89007200236, 0.88806174685, 0.88592301764, 0.88365644848, 0.88126271101, 0.87874251453, 0.87609660583, 0.87332576897, 0.87043082499, 0.86741263173, 0.86427208354, 0.86101011105, 0.85762768083, 0.85412579518, 0.85050549179, 0.84676784342, 0.84291395762, 0.83894497639, 0.83486207581, 0.83066646574, 0.82635938943, 0.82194212315, 0.81741597584, 0.8127822887, 0.80804243479, 0.80319781862, 0.79824987576, 0.79320007239, 0.78804990488, 0.78280089934, 0.77745461115, 0.77201262455, 0.7664765521, 0.76084803426, 0.7551287389, 0.74932036074, 0.74342462096, 0.73744326657, 0.73137806998, 0.72523082845, 0.71900336353, 0.71269752056, 0.70631516808, 0.69985819734, 0.69332852167, 0.68672807596, 0.68005881605, 0.6733227182, 0.66652177845, 0.65965801208, 0.65273345296, 0.64575015299, 0.63871018147, 0.6316156245, 0.62446858434, 0.61727117883, 0.6100255407, 0.602733817, 0.59539816842, 0.58802076867, 0.58060380384, 0.57314947173, 0.56565998122, 0.5581375516, 0.55058441195, 0.54300280041, 0.53539496358, 0.52776315582, 0.52010963861, 0.51243667985, 0.5047465532, 0.49704153742, 0.48932391566, 0.48159597481, 0.47386000485, 0.4661182981, 0.4583731486, 0.4506268514, 0.4428817019, 0.43513999515, 0.42740402519, 0.41967608434, 0.41195846258, 0.4042534468, 0.39656332015, 0.38889036139, 0.38123684418, 0.37360503642, 0.36599719959, 0.35841558805, 0.3508624484, 0.34334001878, 0.33585052827, 0.32839619616, 0.32097923133, 0.31360183158, 0.306266183, 0.2989744593, 0.29172882117, 0.28453141566, 0.2773843755, 0.27028981853, 0.26324984701, 0.25626654704, 0.24934198792, 0.24247822155, 0.2356772818, 0.22894118395, 0.22227192404, 0.21567147833, 0.20914180266, 0.20268483192, 0.19630247944, 0.18999663647, 0.18376917155, 0.17762193002, 0.17155673343, 0.16557537904, 0.15967963926, 0.1538712611, 0.14815196574, 0.1425234479, 0.13698737545, 0.13154538885, 0.12619910066, 0.12095009512, 0.11579992761, 0.11075012424, 0.10580218138, 0.10095756521, 0.096217711298, 0.091584024156, 0.087057876849, 0.082640610574, 0.078333534262, 0.074137924191, 0.070055023613, 0.066086042378, 0.062232156581, 0.058494508212, 0.054874204817, 0.051372319169, 0.047989888954, 0.044727916458, 0.041587368273, 0.038569175013, 0.035674231033, 0.032903394167, 0.030257485474, 0.027737288995, 0.025343551516, 0.023076982356, 0.020938253146, 0.018927997639, 0.017046811517, 0.015295252215, 0.01367383876, 0.012183051609, 0.010823332516, 0.0095950843954, 0.0084986712029, 0.0075344178297, 0.0067026100047, 0.0060034942106, 0.0054372776106, 0.0050041279867, 0.0047041736907, 0.0045375036054, 0.0045041671187, 0.004604174109, 0.0048374949421, 0.00520406048, 0.0057037621013, 0.0063364517338, 0.0071019418977, 0.0080000057619, 0.0090303772107, 0.010192750923, 0.011486782462, 0.012912088378, 0.014468246322, 0.016154795172, 0.017971235167, 0.019917028055, 0.021991597257, 0.024194328034, 0.026524567667, 0.028981625658, 0.031564773926, 0.03427324703, 0.037106242389, 0.040062920528, 0.043142405317, 0.046343784239, 0.049666108656, 0.053108394093, 0.056669620525, 0.060348732685, 0.064144640372, 0.068056218776, 0.072082308813, 0.076221717464, 0.080473218135, 0.084835551014, 0.089307423447, 0.093887510321, 0.098574454459, 0.10336686702, 0.1082633279, 0.11326238618, 0.11836256054, 0.12356233967, 0.12886018277, 0.13425451997, 0.13974375283, 0.14532625475, 0.15100037153, 0.15676442179, 0.16261669753, 0.1685554646, 0.1745789632, 0.18068540845, 0.18687299087, 0.19313987695, 0.19948420967, 0.20590410907, 0.21239767281, 0.21896297669, 0.22559807527, 0.23230100243, 0.23906977195, 0.24590237809, 0.25279679622, 0.25975098335, 0.26676287882, 0.27383040486, 0.28095146719, 0.2881239557, 0.29534574502, 0.30261469518, 0.30992865224, 0.3172854489, 0.3246829052, 0.33211882911, 0.3395910172, 0.3470972553, 0.35463531915, 0.36220297506, 0.36979798057, 0.37741808512, 0.3850610307, 0.39272455255, 0.4004063798, 0.40810423615, 0.41581584057, 0.42353890794, 0.43127114975, 0.43901027477, 0.44675398973, 0.4545],
     "psi": [
    [0.21552201001, 0.21613637639, 0.012720462943, 0.043304737761, 0.2180983633, 0.10855594435, 0.0043234800524, 0.0033256177603, 0.0026360863526, 0.054524601358, 0.043540478094, 0.027138870366, 0.016671814269, 0.010826144548, 0.0074621277594, 0.0054081942383, 0.0040807553588, 0.0031801130667, 0.0025438220329, 0],
    [0.21175904873, 0.21115712488, 0.0081472916449, 0.021194744044, 0.10635740798, 0.21368160982, 0.0057245802407, 0.0042359239153, 0.0032582695831, 0.042658668826, 0.053420416794, 0.042658732231, 0.026589275904, 0.016334189622, 0.010606901694, 0.0073110102791, 0.005298671368, 0.0039981147226, 0.003115711515, 0.0024923061975],
    [0.036353763054, 0.023765426173, 0.61593953929, 0.15441979775, 0.038605012213, 0.024707227325, 0, 0, 0, 0.036353061176, 0.023764957658, 0.016697988527, 0.012355736858, 0.0095040239258, 0.0075334660469, 0, 0, 0, 0, 0],
    [0.083363396762, 0.041644154995, 0.10401512934, 0.41488871103, 0.1040154676, 0.046229132487, 0.0051365924268, 0.0041606426149, 0, 0.083362031755, 0.041643387536, 0.024487017969, 0.016007810251, 0.011247578195, 0.0083226857018, 0.0064018036032, 0.005074457731, 0, 0, 0],
    [0.17240170229, 0.085810963167, 0.010677913105, 0.042711721865, 0.17036515472, 0.17084728408, 0.0034866939718, 0.002669501792, 0.0021092373198, 0.17240176891, 0.085810098103, 0.034230936954, 0.017100015736, 0.010055098747, 0.0065732832853, 0.0046185901564, 0.0034175421304, 0.0026287707119, 0.0020837229529, 0],
    [0.080886991139, 0.16250925771, 0.0064417316196, 0.017893727756, 0.16104379904, 0.16058933501, 0.004473460872, 0.0032866264039, 0.002516324915, 0.08088617912, 0.16250934495, 0.08088630133, 0.032266759628, 0.016118813138, 0.009478134863, 0.0061961066296, 0.0043535741672, 0.0032214425298, 0.0024779309706, 0.001964158209],
    [0.0039118463902, 0.0052866172533, 0, 0.0024142567311, 0.0039909199858, 0.0054320893535, 0.19500240238, 0.19555608693, 0.048889050829, 0.003911767785, 0.0052865117572, 0.0075238949375, 0.011509257549, 0.019573030426, 0.039181488594, 0.098220269113, 0.19733543744, 0.098220390328, 0.039181581787, 0.01957310043],
    [0.0026746790815, 0.0034772297755, 0, 0.0017382801627, 0.002716066655, 0.0035475180941, 0.1738290496, 0.17333688155, 0.17382925651, 0.0026746250774, 0.003477159878, 0.0046991660607, 0.006687969762, 0.010230547527, 0.017398412392, 0.03482831558, 0.087307722752, 0.17541090238, 0.087307820886, 0.034828396281],
    [0.002546916139, 0.0032131271778, 0, 0, 0.0025780498831, 0.0032628466237, 0.052205743498, 0.20882309827, 0.20823160253, 0.0025468645439, 0.0032130622806, 0.0041771578492, 0.0056451697871, 0.0080343455723, 0.012290090133, 0.02090093921, 0.041839708435, 0.10488389582, 0.21072337135, 0.1048840109],
    [0.052352130472, 0.041805656589, 0.01221339472, 0.041578628784, 0.20940856234, 0.10422960953, 0.0041511324793, 0.0031930478215, 0.0025310032085, 0.20693478002, 0.2075161648, 0.051879076863, 0.023057383988, 0.012969787589, 0.0083006698593, 0.0057643579955, 0.0042350413283, 0.0032424556147, 0.0025619418335, 0.0020751741655],
    [0.03532423879, 0.044235687289, 0.0067463708089, 0.017550345871, 0.088070177907, 0.17694279665, 0.0047402417144, 0.0035075585393, 0.0026980112085, 0.17534350755, 0.17485225885, 0.17534374861, 0.04383596912, 0.019482666604, 0.010959007619, 0.0070137696262, 0.004870676544, 0.003578458529, 0.0027397589952, 0.0021647491692],
    [0.025236440769, 0.040488358595, 0.005433179341, 0.011828570104, 0.040268548989, 0.10094533263, 0.007732692262, 0.0054332261177, 0.0040203347127, 0.050244290292, 0.20097729931, 0.20041395852, 0.20097759242, 0.050244432634, 0.02233087442, 0.012561125266, 0.008039125365, 0.0055827294763, 0.0041015996467, 0.003140289121],
    [0.01693078717, 0.027560474234, 0.0043905252828, 0.0084447388834, 0.021968563194, 0.043976895727, 0.012917939986, 0.0084447974534, 0.0059335729048, 0.024387229103, 0.054871303962, 0.21948537589, 0.21886983763, 0.21948567755, 0.054871457555, 0.024387330616, 0.013717882209, 0.008779450089, 0.0060968439648, 0.0044793165974],
    [0.011286349274, 0.017380535231, 0.0034668953344, 0.0060911416128, 0.013261017903, 0.022552134569, 0.022552225365, 0.013261089056, 0.0086691228945, 0.014082205163, 0.025035048956, 0.056328900435, 0.22531575657, 0.22468355843, 0.22531607002, 0.056329053854, 0.025035150643, 0.014082280873, 0.0090126650094, 0.0062587988177],
