=== dd-harp/MicroMoB-connector/schema/aqua_par.json
{
  "$ref": "#/definitions/AquaPar",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AquaPar": {
      "additionalProperties": false,
      "description": "Parameters for the Beverton-Holt aquatic mosquito model.",
      "properties": {
        "stochastic": {
         "items": {
            "type": "boolean"
          },
          "type": "array"
        },
        "molt": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "surv": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "K": {
          "items": {
            "type": "number"
          },
          "type": "array"
        },
        "L": {
          "items": {
            "type": "number"
          },
          "type": "array"
        }
      },
      "required": [
        "stochastic",
        "molt",
        "surv",
        "K",
        "L"
      ],
      "type": "object"
    }
  }
}

=== dd-harp/MicroMoB-connector/test/aqua_par.json
{
  "stochastic": [true],
  "molt": [0.1],
  "surv": [0.9],
  "K": [40.6069418475, 47.0701828044, 53.2941399916, 42.5692552327, 52.755618227, 124.7655699092, 42.1688838122, 124.5659690092, 123.6709789335, 143.8801703253, 99.0549045402, 93.0887307943, 54.3153302924, 92.347798572, 96.3048483008, 79.4404095923, 149.6831462737, 50.2456461652, 73.2737293828, 121.8034931122],
  "L": [266.3815385196, 308.7803991968, 349.6095583448, 279.2543143267, 346.0768555691, 818.4621386044, 276.6278778082, 817.1527567003, 811.2816218035, 943.8539173342, 649.8001737837, 610.6620740108, 356.3085667184, 605.8015586324, 631.7598048532, 521.1290869256, 981.9214395555, 329.6114388434, 480.6756647509, 799.0309148161]
}
